"""Assemble README.md from the curated snippets in ``docs/readme/``.

The README is the project's front door, so it is where hand-maintained prose
and facts derived from the code meet. Editing it in place means every number
in it can be a number that is stale by one release. So the prose lives in
``docs/readme/*.md`` — one file per section, curated — and the *facts* are
substituted from the code at build time:

* ``<!-- gen:cli_table -->`` — the ``comp`` dispatcher and its summaries.
* ``<!-- gen:policy_table -->`` — ``POLICY_CATALOG`` and each policy's docstring.
* ``<!-- gen:demo_table -->`` — the demo scripts on disk and their docstrings.

The contents list is generated too, from the headings the section files
actually contain, so it cannot list a section that was renamed or deleted.

``tests/property/test_readme_build_lock.py`` fails when the committed README
differs from this build, so a snippet edit and a regenerated README are the same
commit.

Usage::

    uv run python docs/readme/build_readme.py [--check]
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SNIPPET_DIR = Path(__file__).resolve().parent
README = REPO / "README.md"

_GENERATED_RE = re.compile(r"<!-- gen:([a-z_]+) -->")

BANNER = (
    "<!-- Generated by docs/readme/build_readme.py from docs/readme/*.md. "
    "Edit the snippets, not this file. -->"
)


def _docstring_first_line(path: Path) -> str:
    """A module's one-line summary, taken from its own docstring."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    doc = ast.get_docstring(tree, clean=True)
    if not doc:
        return ""
    first = doc.splitlines()[0].strip()
    return re.sub(r"^(Demo|Lock|TODO46)\s*:\s*", "", first)


def _cli_table() -> str:
    """The dispatcher's commands, in the order the parser builds them."""
    from computronium.cli.__main__ import _SUMMARIES

    rows = ["| Command | Purpose |", "|---|---|"]
    rows.extend(f"| `{name}` | {summary} |" for name, summary in _SUMMARIES.items())
    return "\n".join(rows)


def _policy_table() -> str:
    """Every registered policy, described by its own docstring."""
    from computronium.experiment.execution.policy import POLICY_CATALOG

    rows = ["| Policy | Key | Behavior |", "|---|---|---|"]
    for name, cls in POLICY_CATALOG.items():
        summary = (cls.__doc__ or "").splitlines()[0].strip()
        rows.append(f"| {cls.__name__} | `{name}` | {summary} |")
    return "\n".join(rows)


def _demo_table() -> str:
    """Every demo script on disk, described by its own docstring."""
    rows = ["| Demo | Shows |", "|---|---|"]
    for path in sorted((REPO / "scripts" / "demos").glob("demo_*.py")):
        rows.append(f"| `{path.name}` | {_docstring_first_line(path)} |")
    return "\n".join(rows)


_GENERATORS = {
    "cli_table": _cli_table,
    "policy_table": _policy_table,
    "demo_table": _demo_table,
}


_PREAMBLE = Path("00-header.md")


def _section_files() -> list[Path]:
    """Snippet files in order; the numeric prefix is the section order.

    The preamble carries the title and is not a numbered section.
    """
    return [p for p in sorted(SNIPPET_DIR.glob("[0-9][0-9]-*.md")) if p != _PREAMBLE]


def _anchor(heading: str) -> str:
    """GitHub's heading slug: lowercase, punctuation dropped, spaces hyphenated.

    Each space becomes its own hyphen, so "Evidence & claims" anchors as
    ``evidence--claims`` — the ampersand leaves the two words separated.
    """
    return re.sub(r"[\s]", "-", re.sub(r"[^\w\s-]", "", heading.lower()).strip())


def _contents(sections: str) -> str:
    """The section list, derived from the headings that actually exist."""
    lines = ["## Contents", ""]
    for heading in re.findall(r"^## (.+)$", sections, flags=re.M):
        lines.append(f"- [{heading}](#{_anchor(heading)})")
    return "\n".join(lines) + "\n\n---"


def _substitute(text: str) -> str:
    def replace(match: re.Match[str]) -> str:
        name = match.group(1)
        if name not in _GENERATORS:
            msg = f"unknown generated block {name!r}"
            raise KeyError(msg)
        return _GENERATORS[name]()

    return _GENERATED_RE.sub(replace, text)


def build_readme() -> str:
    """Render the README from every snippet, in section order."""
    files = _section_files()
    if not files:
        msg = f"no snippets found in {SNIPPET_DIR}"
        raise FileNotFoundError(msg)
    preamble = (SNIPPET_DIR / _PREAMBLE.name).read_text(encoding="utf-8").rstrip()
    parts = [path.read_text(encoding="utf-8").rstrip() for path in files]
    sections = "\n\n".join(parts)
    return (
        "\n\n".join((BANNER, preamble, _contents(sections), _substitute(sections)))
        + "\n"
    )


def main(argv: list[str] | None = None) -> int:
    """Write README.md, or report drift with ``--check``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if README.md differs from the snippets (no write)",
    )
    args = parser.parse_args(argv)

    rendered = build_readme()
    if args.check:
        current = README.read_text(encoding="utf-8") if README.exists() else ""
        if current != rendered:
            print(
                "README.md is stale; run `uv run python docs/readme/build_readme.py`",
                file=sys.stderr,
            )
            return 1
        return 0

    README.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
