# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from computronium.p2p.proto import (
    tile_mesh_pb2 as computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2,
)

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in computronium/p2p/proto/tile_mesh_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TileMeshServiceStub:
    """RPC Service for Tile Mesh Communication"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchTileActivation = channel.unary_unary(
            "/bioplausible.p2p.TileMeshService/FetchTileActivation",
            request_serializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.TileActivationRequest.SerializeToString,
            response_deserializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.TileActivationResponse.FromString,
            _registered_method=True,
        )
        self.SyncBoundaryTiles = channel.unary_unary(
            "/bioplausible.p2p.TileMeshService/SyncBoundaryTiles",
            request_serializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.BoundarySyncRequest.SerializeToString,
            response_deserializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.BoundarySyncResponse.FromString,
            _registered_method=True,
        )
        self.Heartbeat = channel.unary_unary(
            "/bioplausible.p2p.TileMeshService/Heartbeat",
            request_serializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.HeartbeatRequest.SerializeToString,
            response_deserializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.HeartbeatResponse.FromString,
            _registered_method=True,
        )
        self.PushParameterUpdate = channel.unary_unary(
            "/bioplausible.p2p.TileMeshService/PushParameterUpdate",
            request_serializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.ParameterUpdateRequest.SerializeToString,
            response_deserializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.ParameterUpdateResponse.FromString,
            _registered_method=True,
        )
        self.ExecuteStep = channel.unary_unary(
            "/bioplausible.p2p.TileMeshService/ExecuteStep",
            request_serializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.ExecuteStepRequest.SerializeToString,
            response_deserializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.ExecuteStepResponse.FromString,
            _registered_method=True,
        )


class TileMeshServiceServicer:
    """RPC Service for Tile Mesh Communication"""

    def FetchTileActivation(self, request, context):
        """Fetch activation for a remote tile"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SyncBoundaryTiles(self, request, context):
        """Synchronize boundary tile activations with neighbor"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Heartbeat(self, request, context):
        """Send heartbeat to maintain P2P membership"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PushParameterUpdate(self, request, context):
        """Federated parameter update aggregation"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExecuteStep(self, request, context):
        """Execute a single distributed training step"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TileMeshServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "FetchTileActivation": grpc.unary_unary_rpc_method_handler(
            servicer.FetchTileActivation,
            request_deserializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.TileActivationRequest.FromString,
            response_serializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.TileActivationResponse.SerializeToString,
        ),
        "SyncBoundaryTiles": grpc.unary_unary_rpc_method_handler(
            servicer.SyncBoundaryTiles,
            request_deserializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.BoundarySyncRequest.FromString,
            response_serializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.BoundarySyncResponse.SerializeToString,
        ),
        "Heartbeat": grpc.unary_unary_rpc_method_handler(
            servicer.Heartbeat,
            request_deserializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.HeartbeatRequest.FromString,
            response_serializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.HeartbeatResponse.SerializeToString,
        ),
        "PushParameterUpdate": grpc.unary_unary_rpc_method_handler(
            servicer.PushParameterUpdate,
            request_deserializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.ParameterUpdateRequest.FromString,
            response_serializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.ParameterUpdateResponse.SerializeToString,
        ),
        "ExecuteStep": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteStep,
            request_deserializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.ExecuteStepRequest.FromString,
            response_serializer=computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.ExecuteStepResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "bioplausible.p2p.TileMeshService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "bioplausible.p2p.TileMeshService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.


class TileMeshService:
    """RPC Service for Tile Mesh Communication"""

    @staticmethod
    def FetchTileActivation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/bioplausible.p2p.TileMeshService/FetchTileActivation",
            computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.TileActivationRequest.SerializeToString,
            computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.TileActivationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SyncBoundaryTiles(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/bioplausible.p2p.TileMeshService/SyncBoundaryTiles",
            computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.BoundarySyncRequest.SerializeToString,
            computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.BoundarySyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Heartbeat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/bioplausible.p2p.TileMeshService/Heartbeat",
            computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.HeartbeatRequest.SerializeToString,
            computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PushParameterUpdate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/bioplausible.p2p.TileMeshService/PushParameterUpdate",
            computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.ParameterUpdateRequest.SerializeToString,
            computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.ParameterUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExecuteStep(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/bioplausible.p2p.TileMeshService/ExecuteStep",
            computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.ExecuteStepRequest.SerializeToString,
            computronium_dot_p2p_dot_proto_dot_tile__mesh__pb2.ExecuteStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
