import pathlib

from bioplausible.knowledge.metamodel import KnowledgebaseMetamodel


def main():
    print("Testing Phase 1.6: Knowledgebase Metamodel...")

    # We will point it at the mock DB generated by Phase 1.5's test
    db_path = "results/test_failures.db"

    if not pathlib.Path(db_path).exists():
        print(
            f"Error: {db_path} not found. Please run scripts/run_manifesto_test.py first."
        )
        return

    metamodel = KnowledgebaseMetamodel()
    metamodel.fit(db_path)

    if not metamodel.fitted:
        print("Metamodel failed to fit.")
        return

    print("\n--- Extracted Symbolic Rules (EqProp) ---")
    rules = metamodel.extract_symbolic_rules(focus_model="eqprop_mlp")
    for rule in rules:
        print(rule)

    print("\n--- Algorithm Similarity Matrix ---")
    sim_matrix = metamodel.compute_algorithm_similarity()
    if sim_matrix.empty:
        print("Not enough diverse data to compute similarities.")
    else:
        print(sim_matrix.to_string())

    print("\nMetamodel test complete.")


if __name__ == "__main__":
    main()
