"""Layer 1: Substrate — Physical State Space Constraints."""

from computronium.ontology.substrate._substrate import (
    AnalogSubstrate,
    ComplexSubstrate,
    DigitalSubstrate,
    MemristiveSubstrate,
    NeuromorphicSubstrate,
    NoisySubstrate,
    OpticalSubstrate,
    QuantizedSubstrate,
    QuantumSubstrate,
    SparseSubstrate,
    Substrate,
    SubstrateConfig,
    SubstrateType,
    TernarySubstrate,
    substrate_from_config,
)
from computronium.ontology.substrate.spec import (
    ConstraintConfig,
    CostConfig,
    DeviceModel,
    ExecutionModel,
    NoiseConfig,
    NumericRepresentation,
    SubstrateSpec,
    make_substrate,
)

__all__ = [
    "AnalogSubstrate",
    "ComplexSubstrate",
    "ConstraintConfig",
    "CostConfig",
    "DeviceModel",
    "DigitalSubstrate",
    "ExecutionModel",
    "MemristiveSubstrate",
    "NeuromorphicSubstrate",
    "NoiseConfig",
    "NoisySubstrate",
    "NumericRepresentation",
    "OpticalSubstrate",
    "QuantizedSubstrate",
    "QuantumSubstrate",
    "SparseSubstrate",
    "Substrate",
    "SubstrateConfig",
    "SubstrateSpec",
    "SubstrateType",
    "TernarySubstrate",
    "make_substrate",
    "substrate_from_config",
]
