"""Accessibility package."""

from computronium.ui.a11y.audit import (
    AxeResult,
    AxeViolation,
    KeyboardCheckResult,
    ci_axe_scan,
    format_axe_report,
    has_critical_or_serious,
    run_axe_scan,
    run_keyboard_crawl,
    violations_by_severity,
)
from computronium.ui.a11y.tokens import (
    FOCUS_DEFAULT,
    FOCUS_HIGH_CONTRAST,
    FOCUS_WHITE_ON_DARK,
    LIVE_REGION_CONFIG,
    MIN_TOUCH_TARGET,
    MOTION,
    RECOMMENDED_TOUCH_TARGET,
    TEXT_SPACING,
    TOUCH_TARGET_GAP,
    a11y_css,
    contrast_ratio,
    meets_aa,
    meets_aaa,
    meets_ui,
)

__all__ = [
    "FOCUS_DEFAULT",
    "FOCUS_HIGH_CONTRAST",
    "FOCUS_WHITE_ON_DARK",
    "LIVE_REGION_CONFIG",
    "MIN_TOUCH_TARGET",
    "MOTION",
    "RECOMMENDED_TOUCH_TARGET",
    "TEXT_SPACING",
    "TOUCH_TARGET_GAP",
    "AxeResult",
    "AxeViolation",
    "KeyboardCheckResult",
    "a11y_css",
    "ci_axe_scan",
    "contrast_ratio",
    "format_axe_report",
    "has_critical_or_serious",
    "meets_aa",
    "meets_aaa",
    "meets_ui",
    "run_axe_scan",
    "run_keyboard_crawl",
    "violations_by_severity",
]
